### ISSUE TITLE
Iris not starting

### ISSUE THREAD

**Issue by JanJaapKo** [jaedb/Iris#506]
Yesterday I did a clean instal of my RPi 3b after upgrading several times, I decided to do a clean install of Buster. I followed all the installation steps of first mopidy, mopidy-spotify, all fine. Mopidy running as a service. Then I installed Iris via pip as on the Wiki without errors and run into 2 issues:

At step 2 of the installation (setting permisions) I get the error:
`-bash: /etc/sudoers: Permission denied`
I guess it doesn't really matter as it only allows Iris to change configs, it should start anyway?

The bigger issue is that Iris isn't started. 
- When accessing the url: `http://_myip_:6680/mopidy/` Iris is not shown as extension
- when accessing the url: `http://_myip_:6680/iris/#/` I get a 404 not found error
- when checking location `/usr/local/lib/python3.7/dist-packages/` Iris is not there
- when checking pip installed packages, Iris is there:

`pi@raspberrypi:~ $ pip3 list
Package        Version
-------------- ---------
asn1crypto     0.24.0
certifi        2018.8.24
chardet        3.0.4
crypto         1.4.1
cryptography   2.6.1
entrypoints    0.3
idna           2.6
keyring        17.1.1
keyrings.alt   3.1.1
Mopidy         3.0.1
Mopidy-Iris    3.45.1
Mopidy-Spotify 4.0.1
Naked          0.1.31
pip            18.1
pycrypto       2.6.1
PyGObject      3.30.4
Pykka          2.0.2
pyspotify      2.1.3
python-apt     1.8.4.1
pyxdg          0.25
PyYAML         5.3
requests       2.21.0
SecretStorage  2.3.1
setuptools     40.8.0
shellescape    3.8.1
six            1.12.0
ssh-import-id  5.7
tornado        5.1.1
urllib3        1.24.1
wheel          0.32.3
`

**Comment by el97** [comment]
Can you post your config for mopidy and the log using the `sudo journalctl -u mopidy` command?

**Comment by JanJaapKo** [comment]
The config:
`
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
verbosity = 0
format = %(levelname)-8s [%(threadName)s] %(name)s %(message)s
color = false
config_file = /etc/mopidy/logging.conf

[audio]
mixer = software
mixer_volume = 100
output = alsasink device=hw:1,0
buffer_time =

[proxy]
scheme =
hostname =
port =
username =
password =

[file]
enabled = true
media_dirs =
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions =
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .pdf
  .png
  .txt
  .zip
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[http]
enabled = true
hostname = 192.168.1.16
port = 6680
zeroconf = Mopidy HTTP server on $hostname
allowed_origins =
csrf_protection = true
default_app = mopidy

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /var/lib/mopidy/playlists

[softwaremixer]
enabled = true

[stream]
enabled = true
protocols =
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist =
timeout = 5000

[spotify]
enabled = true
username = jan-jaap.kostelijk
password = ********
client_id = 981011cc-3e04-41c8-bec6-5aa8efe8a117
client_secret = ********
bitrate = 320
volume_normalization = true
private_session = false
timeout = 10
allow_cache = true
allow_network = true
allow_playlists = true
search_album_count = 20
search_artist_count = 10
search_track_count = 50
toplist_countries =
  NL
  US
  GB
  DE
`

the status:
`
-- Logs begin at Thu 2019-02-14 11:11:59 CET, end at Mon 2020-03-02 20:50:01 CET. --
Feb 29 12:24:13 raspberrypi systemd[1]: Starting Mopidy music server...
Feb 29 12:24:13 raspberrypi systemd[1]: Started Mopidy music server.
Feb 29 12:24:20 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.__main__ Enabled extensions: softwaremixer, m3u, stream, file, spotify, http
Feb 29 12:24:20 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Feb 29 12:24:21 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Feb 29 12:24:21 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Mixer volume set to 100
Feb 29 12:24:21 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Feb 29 12:24:21 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend, SpotifyBackend
Feb 29 12:24:21 raspberrypi mopidy[541]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink device=hw:1,0"
Feb 29 12:24:22 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
Feb 29 12:24:22 raspberrypi mopidy[541]: INFO     [SpotifyBackend-6] mopidy_spotify.web Logged into Spotify Web API as jan-jaap.kostelijk
Feb 29 12:24:32 raspberrypi mopidy[541]: INFO     [SpotifyBackend-6] mopidy_spotify.playlists Refreshed 32 Spotify playlists
Feb 29 12:24:32 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Feb 29 12:24:32 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend
Feb 29 12:24:32 raspberrypi mopidy[541]: INFO     [HttpFrontend-11] mopidy.http.actor HTTP server running at [::ffff:192.168.1.16]:6680
Feb 29 12:24:32 raspberrypi mopidy[541]: INFO     [MainThread] mopidy.commands Starting GLib mainloop
Mar 02 02:14:45 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:14:45 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:14:54 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:14:54 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:15:06 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:15:06 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:15:28 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:15:28 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:16:07 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:16:07 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:17:00 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:17:00 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:18:28 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:18:28 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:20:45 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:20:45 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:24:17 raspberrypi mopidy[541]: ERROR    [SpotifyEventLoop] spotify.session Spotify connection error: <ErrorType.UNABLE_TO_CONTACT_SERVER: 8>
Mar 02 02:24:17 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Disconnected from Spotify
Mar 02 02:28:35 raspberrypi mopidy[541]: INFO     [SpotifyEventLoop] mopidy_spotify.backend Logged in to Spotify in online mode
~
`

**Comment by DDomnick** [comment]
Exact same problem.

-- Logs begin at Mon 2020-03-02 15:46:30 EST, end at Mon 2020-03-02 16:01:46 EST. --
Mar 02 15:46:35 raspberrypi systemd[1]: Starting Mopidy music server...
Mar 02 15:46:35 raspberrypi systemd[1]: Started Mopidy music server.
Mar 02 15:46:41 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.__main__ Starting Mopidy 3.0.1
Mar 02 15:46:41 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.config Loading config from builtin defaults
Mar 02 15:46:41 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.config Loading config from file:///usr/share/mopidy/conf.d/mopidy.conf
Mar 02 15:46:41 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.config Loading config from file:///etc/mopidy/mopidy.conf
Mar 02 15:46:41 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.config Loading config from command line options
Mar 02 15:46:42 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.__main__ Enabled extensions: stream, mpd, http, m3u, file, softwaremixer
Mar 02 15:46:42 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.__main__ Disabled extensions: none
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting Mopidy mixer: SoftwareMixer
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting Mopidy audio
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting Mopidy backends: FileBackend, M3UBackend, StreamBackend
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [Audio-2] mopidy.audio.actor Audio output set to "alsasink"
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: HttpFrontend, MpdFrontend
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [HttpFrontend-8] mopidy.http.actor HTTP server running at [::]:6680
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::]:6600
Mar 02 15:46:44 raspberrypi mopidy[412]: INFO     [MainThread] mopidy.commands Starting GLib mainloop

**Comment by jaedb** [comment]
How are you installing Iris and Mopidy? `pip3` might show Iris, but it looks like Mopidy is not recognizing it, this could be due to a number of things including installing Iris with python2, but running Mopidy with python 3. Or more likely you're not including `sudo`, ie: `sudo python3 -m pip install mopidy-iris`.

**Comment by el97** [comment]
This might not be the solution but I had to disable local-images in `/etc/mopidy/mopidy.conf` to make it work. Otherwise I would get this error when i look at the status using `sudo service mopidy status
`:
`File "/usr/local/lib/python3.7/dist-packages/mopidy_local_images/library.py", line 12, in <module>`
`ImportError: cannot import name 'local' from 'mopidy' (/usr/lib/python3/dist-packages/mopidy/__init__.py)`

**Comment by kingosticks** [comment]
> This might not be the solution but I had to disable local-images 

It's not, but it should be fixed.

From https://docs.mopidy.com/en/latest/changelog/:
> Mopidy-Local merged with Mopidy-Local-SQLite and Mopidy-Local-Images, which are now both a part of the Mopidy-Local extension.

So remove the Mopidy-Local-Images extension. It's not required in Mopidy 3 (and is not supported).

@jaedb Can maybe update your wiki installation page. It looks like you are suggesting [running Mopidy as a service](https://docs.mopidy.com/en/latest/running/service/) (a good idea) in which case the install instructions need to include `sudo`. Otherwisie pip installation without `sudo` will install Iris under `~/` instead, meaning the service won't find the Iris installation (and also making step 2 pretty pointless).

And similarly, if you advocating the service then the 'typical' config file location should probably be changed to `/etc/mopidy/mopidy.conf`, and not `~/.config/mopidy/mopidy.conf`. Or the distiction made a bit clearer. We tried to improve this part of the Mopidy docs as part of the 3.0 release, you could link to our docs.

Please also remove the mention of Mopidy-Local-SQLite (which no longer exists, see changelog quote above).

**Comment by jaedb** [comment]
@kingosticks fair points, consider them addressed,

**Comment by JanJaapKo** [comment]
Hi,

Installing Iris as sudo indeed did the installation. However, at step 2 I still get an error:

pi@raspberrypi:~ $ sudo echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers
-bash: /etc/sudoers: Permission denied

My installation is a clean install. File sudoers has below permissions:

pi@raspberrypi:/etc $ ls -l | grep "sudoers"
-r--r----- 1 root root     669 Feb  2 08:41 sudoers
drwxr-xr-x 2 root root    4096 Feb 28 22:45 sudoers.d

Should I add write acces for root to it? Can I do that?

**Comment by auras** [comment]
> How are you installing Iris and Mopidy? `pip3` might show Iris, but it looks like Mopidy is not recognizing it, this could be due to a number of things including installing Iris with python2, but running Mopidy with python 3. Or more likely you're not including `sudo`, ie: `sudo python3 -m pip install mopidy-iris`.

But how does Mopidy detect extensions? Maybe there's something wrong with the install process and we have to manually configure mopidy to point to the iris extension.

**Comment by kingosticks** [comment]
Are you saying you **did** install using sudo and you are still experiencing problems? Because if you didn't, that's the problem, so do that.

**Comment by hazardlabs** [comment]
I can confirm having the same experience:

Fresh install of Raspbian Buster Lite then enter the following commands:

`sudo apt install mopidy`

`sudo usermod -aG sudo mopidy` --To see if this got around the permissions issue as 

`sudo echo "mopidy ALL=NOPASSWD: /usr/local/lib/python3.7/dist-packages/mopidy_iris/system.sh" >> /etc/sudoers` 

gives the error

`-bash: /etc/sudoers: Permission denied`

`sudo apt install python3-pip`

`sudo python3 - m pip install Mopidy-Iris`

Output of sudo mopidyctl config:

`$ sudo mopidyctl config
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf config" as user mopidy
/usr/lib/python2.7/dist-packages/mopidy/ext.py:202: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  extension_class = entry_point.load(require=False)
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy
max_tracklist_length = 10000
restore_state = false

[logging]
color = true
console_format = %(levelname)-8s %(message)s
debug_format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
debug_file = /var/log/mopidy/mopidy-debug.log
config_file = /etc/mopidy/logging.conf

[audio]
mixer = software
mixer_volume = 
output = autoaudiosink
buffer_time = 

[proxy]
scheme = 
hostname = 
port = 
username = 
password = 

[mpd]
enabled = true
hostname = 127.0.0.1
port = 6600
password = 
max_connections = 20
connection_timeout = 60
zeroconf = Mopidy MPD server on $hostname
command_blacklist = 
  listall
  listallinfo
default_playlist_scheme = m3u

[http]
enabled = true
hostname = 127.0.0.1
port = 6680
static_dir =
zeroconf = Mopidy HTTP server on $hostname
allowed_origins = 
csrf_protection = true

[stream]
enabled = true
protocols = 
  http
  https
  mms
  rtmp
  rtmps
  rtsp
metadata_blacklist = 
timeout = 5000

[m3u]
enabled = true
base_dir =
default_encoding = latin-1
default_extension = .m3u8
playlists_dir = /var/lib/mopidy/playlists

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs = 
  $XDG_MUSIC_DIR|Music
  ~/|Home
excluded_file_extensions = 
  .jpg
  .jpeg
show_dotfiles = false
follow_symlinks = false
metadata_timeout = 1000

[local]
enabled = true
library = json
media_dir = /var/lib/mopidy/media
scan_timeout = 1000
scan_flush_threshold = 100
scan_follow_symlinks = false
excluded_file_extensions = 
  .directory
  .html
  .jpeg
  .jpg
  .log
  .nfo
  .png
  .txt
`

End result, cant access the Iris web interface.

**Comment by kingosticks** [comment]
You've installed an old Python 2.7 version of Mopidy from the Debian APT repository. Install latest Mopidy from apt.mopidy.com as described at https://docs.mopidy.com/en/latest/installation/debian/#install-from-apt-mopidy-com

**Comment by hazardlabs** [comment]
@kingosticks thank you for spotting my mistake.

I still had the same issue, however it was fixed by changing the hostname in the [http] section of the config file in `/etc/mopidy/mpoidy.conf`

Was:
`hostname=127.0.0.1`

to:

`hostname=0.0.0.0`

**Comment by auras** [comment]
I think I found the issue for me. The apt install method for mopidy only has only version 2.2.2 (for ARM at least). While the pip version of mopidy-iris, which I have installed, requires mopidy 3.x.

**Comment by kingosticks** [comment]
So, install Mopidy from apt.mopidy.com as per the Mopidy documentation (which is linked from the iris install wiki). The latest version for all architectures is available there. Then install iris from pip using sudo.

**Comment by auras** [comment]
@kingosticks Nope, for arm it's only 2.2.2 available: 


```
pi@tomnook:/etc/init.d $ apt search mopidy                                                                                                             Sorting... Done                                                                                                                                        Full Text Search... Done                                                                                                                               gir1.2-playerctl-2.0/stable 2.0.1-1 armhf                                                                                                                utility to control media players via MPRIS (gir bindings)                                                                                                                                                                                                                                                   libplayerctl-dev/stable 2.0.1-1 armhf                                                                                                                    utility to control media players via MPRIS (development files)                                                                                                                                                                                                                                              libplayerctl-doc/stable 2.0.1-1 all                                                                                                                      utility to control media players via MPRIS (documentation)                                                                                                                                                                                                                                                  libplayerctl2/stable 2.0.1-1 armhf                                                                                                                       utility to control media players via MPRIS (library)                                                                                                                                                                                                                                                        mopidy/stable,now 2.2.2-1 all [installed]                                                                                                                music server with support for MPD/HTTP clients
--
```

**Comment by kingosticks** [comment]
Nope. For Buster, v3.x is available for all architectures from apt.mopidy.com.

**Comment by auras** [comment]
Yeah, but not for jessie, which is Raspbian

**Comment by kingosticks** [comment]
Raspbian is based on Debian Buster and has been since June 2019. It would have been worth mentioning you are running an old operating system.

**Comment by auras** [comment]
Hm... You are right. I just installed via Raspberry Pi Imager last night and it installed me an older version of raspbian, I didn't imagine it wasn't the latest one, sorry.

**Comment by kingosticks** [comment]
Not to worry, honest mistake. Buster has lots of important updates so worth upgrading for sure!

**Comment by JanJaapKo** [comment]
by fixing the instruction to use sudo pip and #509 my issues were solved. This issue can be closed.
