### ISSUE TITLE
Empty Pages: Tracks, Add to playlist

### ISSUE THREAD

**Issue by LimitlessGreen** [jaedb/Iris#520]
**Description**
I installed the latest pip3 version of Mopidy-Iris (3.46.0). I have this issue since several Iris versions.
The problem is, that I get an empty page at some points of Iris.

**Where I get the empty pages?**
1. On Tracks page
2. If I right click on a sound track and say: "Add to playlist"

When I was on a blank page, I have to reload. "Arrow left" doesn't work.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/15064073/78347709-2dfd9780-75a1-11ea-8cb1-47434abb51c6.png)

**Environment details:**
 - OS: Manjaro on RPi 4
 - Browser [Firefox]
 - Iris version [PIP 3.46.0]

**Additional context**
On my phone the Tracks page works, but I also get an empty screen on the "Add to playlist" part.

**Comment by jaedb** [comment]
There is a bit more information that would be really helpful:
1. Enable test mode under _Settings > Debug > Test mode_
2. Open your browser _Developer console_ and paste the output of this when your screen goes blank
3. What Mopidy extensions do you have installed?
4. Have you Authenticated Spotify?

**Comment by tennisparty** [comment]
I had this issue. Albums and artists would briefly (less than a second) show and then disappear leaving a blank screen (on safari/ chrome on Mac Catalina and on chrome on android). When I opened the developer settings it was an issue with the gmusic plugin which didn't have the right credentials in the mopidy.conf file. I uninstalled the google music plugin and now all is working.

**Comment by jaedb** [comment]
@tennisparty awesome, thanks for this input. That helps me trace the issue to the GMusic plugin. I'll investigate this further and see what might be involved to fix this.

**Comment by tennisparty** [comment]
Nice. Actually since, everything is working on my computer but still happens on chrome and duck duck go (on android 10) for me. Iris appears then the screen goes black after a second and won't reappear. Is there anyway I could help you debug this?

**Comment by jaedb** [comment]
@tennisparty are you able to provide more information on the error for those browsers? Especially:
1. Enable test mode under Settings > Debug > Test mode
2. Open your browser Developer console and paste the output of this when your screen goes blank
3. What Mopidy extensions do you have installed?
4. Have you Authenticated Spotify?

**Comment by jaedb** [comment]
@tennisparty I believe the original issue has been resolved, but if it persists for you, please feel free to open a new issue with the information described in my previous comment.
Please note you may need to clear your browser cache on your mobile browsers for the update to take effect.

**Comment by tennisparty** [comment]
Thankyou so much, I didn't know how to enter developer mode on android, sorry. I've updated the app and re-entered my Spotify auth and it is all working. On both my mac and... my android! :) Thanks again.

**Comment by LimitlessGreen** [comment]
@jaedb sorry, I was a bit out of time. 
I'm running 3.47 now, problem is still there.

<details>
<summary>1. My Testmode-Console-Output if I try to add something to a playlist:</summary>
    
```
Test mode enabled, using un-minified code iris:131:11
Download the React DevTools for a better development experience: https://fb.me/react-devtools react-dom.development.js:27773
The above error occurred in the <div> component:
    in div (created by Notifications)
    in div (created by Notifications)
    in span (created by Notifications)
    in div (created by Notifications)
    in Notifications (created by Context.Consumer)
    in Connect(Notifications) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in Connect(App) (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:21843
Error: Objects are not valid as a React child (found: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data). If you meant to render a collection of children, use an array instead.
    in div (created by Notifications)
    in div (created by Notifications)
    in span (created by Notifications)
    in div (created by Notifications)
    in Notifications (created by Context.Consumer)
    in Connect(Notifications) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in Connect(App) (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider react-dom.development.js:14748
Error: Objects are not valid as a React child (found: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data). If you meant to render a collection of children, use an array instead.
    in div (created by Notifications)
    in div (created by Notifications)
    in span (created by Notifications)
    in div (created by Notifications)
    in Notifications (created by Context.Consumer)
    in Connect(Notifications) (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in Connect(App) (created by Context.Consumer)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider react-dom.development.js:14748

```
  
</details>

2. Enabled extensions: `mpd, party, http, local, local-images, iris, stream, m3u, youtube, softwaremixer, file, musicbox_webclient, orfradio`

3. I don't have authenticated Spotify yet.

**Comment by juliusvaart** [comment]
Hi @jaedb 

I'm experiencing the same issue as @LimitlessGreen and the same console errors. 
Also running on a Pi4 4gb. 

My installation is on DietPi. All packages the latest version and running on Python3.

My extra extensions are: `mpd, tunein, alsamixer, spotify, iris`

**Comment by Barpfotenbaer** [comment]
Exactly the same issue here, screen remains blank. After reloading sometimes content becomes visible. After entering text to the search form, screen always remains black (and blank)!

Server: 
* Manjaro-Linux
* mopidy  3.1.1-1
* mopidy-iris 3.56.1-1

Client: 
* Ubuntu-Touch Xenial 16.04 (OTA-16)
* Morph-Browser OR Onion-Browser

**Comment by LimitlessGreen** [comment]
Maybe you should look into the mentioned issue.
`localStorage.clear()` typed into the browser console was the fix for me.
