### ISSUE TITLE
Genres not loading "Could not load category. specified id does not exist"

### ISSUE THREAD

**Issue by rpelletierrefocus** [jaedb/Iris#729]
**Describe the bug**
I click on Genres/Mood then I click on "Top Lists" for example and I get the error "Could not load category. specified id does not exist"

**Expected behavior**
[A clear and concise description of what you expected to happen]

**Console log**
Console log gives me error Failed to load resource: the server responded with a status of 404 ()  https://api.spotify.com/v1/browse/categories/undefined?country=NZ&locale=en_NZ

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Environment details:**
Ubuntu 20.04
Chrome
Iris: 3.57.4

Using Docker from Iris official repo

**Comment by cr45hmurphy** [comment]
Having the same issue. Same setup as @rpelletierrefocus, but utilizing Safari on iOS. One thing of note is that if I perform a 3D touch on the genre/mood square, it actually brings up the corresponding genre/mood playlists within the preview window. For example, 3D touching on the Chill genre brings up various Chill playlists within the preview window. However, going forward still says, "Could not load category. Specified ID does not exist".

I will attach screenshots shortly.

**Comment by rpelletierrefocus** [comment]
This issue also seems to be effecting the Discover page. When I type, Pop, for example. It returns nothing under genre and I get the erro

![Image 224](https://user-images.githubusercontent.com/47399964/113754955-c57a5680-96dd-11eb-9c63-dffd99b8662a.png)

```
{
    "error": {
        "status": 400,
        "message": "No search query"
    },
    "message": "Could not load autocomplete results",
    "description": "No search query",
```

**Comment by Morta1985** [comment]
I have the same issue with:
Arch Linux Kernel 5.11
Firefox
Mopidy-Iris 3.57.4

Installed with python pip

**Comment by jaedb** [comment]
I believe this issue is related to the URIs fix (86f63b89b40e4f0956d578451eae5f82278e55cd). But because you're all on the latest version (which includes this fix) I can only assume it's a build-related issue.

I will version bump with a new build shortly to see if that resolves this. Please upgrade to 3.57.5 and re-test (make sure you clear your browser cache and restart Mopidy after upgrading).

**Comment by Morta1985** [comment]
I have restarted even rebooted and upgraded to the latest Mopidy-Iris trought python pip and dosen‘t fix the issue

**Comment by jaedb** [comment]
The critical thing is clearing your browser cache. Please do this and/or try using an Incognito browser window. Without doing this your browser may still be using the previously-cached version of Iris.

**Comment by cr45hmurphy** [comment]
> 
> 
> The critical thing is clearing your browser cache. Please do this and/or try using an Incognito browser window. Without doing this your browser may still be using the previously-cached version of Iris.

Can confirm that clearing the cache is necessary. Upgraded to 3.57.5. Cleared cache on both desktop and phone. Genre/Mood tiles appear to be working as expected now.

**Comment by jaedb** [comment]
Resolved by clearing caches after upgrading Iris.

**Comment by rpelletierrefocus** [comment]
I can confirm this works with regards to the Genre/Mood page, but NOT for the Discover page. GENRES still show up blank when doing a search. Thank you for your efforts @jaedb

**Comment by jaedb** [comment]
@rpelletierrefocus at what point do you get the blank screen? Can you please provide a screen recording of this in action (in _Test Mode_ with developer console open)? I haven't been able to replicate the issue.
