### ISSUE TITLE
Podcast cover missing and episode list page is blank or infinite spinner

### ISSUE THREAD

**Issue by aryo-sr** [jaedb/Iris#837]
### Iris version

3.62.0

### Operating system(s) affected

- [ ] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [ ] Firefox
- [X] Chrome
- [ ] Edge
- [ ] Other

### What happened?

When I browse the podcast (with ext. Mopidy-Podcast installed), some podcast covers are not showing. Then by clicking them I just got blank page (or infinite spinning spinner), and the only hint I got was the attached logs below.

In other client like musicbox webclient, as well as MPD client like Cantata, clicking the podcast with missing cover will show the episodes list.

I didn't try curl-ing the feed url, as it perhaps blocked by the server. Or perhaps it's caused by url redirection, since the first feed url in the logs below is redirected to different address.

### Logs

```shell
WARNING  [PodcastBackend-12] mopidy_podcast.library No such track: podcast+http://podcasts.nytimes.com/services/xml/rss/nyt/podcasts/freakonomicsradio.xml
WARNING  [PodcastBackend-12] mopidy_podcast.library No such track: podcast+http://learningenglish.voanews.com/podcast/?count=20&zoneId=987
```

**Comment by jaedb** [comment]
@aryo-sr I believe the issue will have been resolved in v3.66. Can you please confirm?

**Comment by aryo-sr** [comment]
Hi @jaedb, thank you for the update!
Even with the most recent version of Mopidy-Podcast (3.0.1), I'm still experiencing the problem..
Details are as follows:

![image](https://user-images.githubusercontent.com/98627850/220070421-928c3795-b919-4b8a-a033-046c7428ddc0.png)

In mopidy.conf:

```
[podcast]
enabled = true
browse_root = /home/pi/Musik/noredir.opml
```

OPML file:
```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.1">
    <head>
        <title>Cantata Podcasts</title>
        <dateCreated>20 Feb 2023 16:33:09 +0700</dateCreated>
        <dateModified>20 Feb 2023 16:33:09 +0700</dateModified>
    </head>
    <body>
        <outline description="" imageUrl="https://gdb.voanews.com/0684E143-CA54-4C31-BBC7-C26E19B2FB70.jpg" text="Learning English Broadcast - VOA Learning English" type="rss" xmlUrl="http://learningenglish.voanews.com/podcast/?count=20&amp;zoneId=1689"/>
        <outline description="" imageUrl="https://image.simplecastcdn.com/images/2be48404-a43c-4fa8-a32c-760a3216272e/fab1584e-8ea9-4efa-9650-5e595861b2cd/3000x3000/image.jpg?aid=rss_feed" text="Freakonomics Radio" type="rss" xmlUrl="http://podcasts.nytimes.com/services/xml/rss/nyt/podcasts/freakonomicsradio.xml"/>
        <outline description="" imageUrl="https://image.simplecastcdn.com/images/2be48404-a43c-4fa8-a32c-760a3216272e/fab1584e-8ea9-4efa-9650-5e595861b2cd/3000x3000/image.jpg?aid=rss_feed" text="Freakonomics Radio" type="rss" xmlUrl="https://feeds.simplecast.com/Y8lFbOT4"/>
    </body>
</opml>
```

I give both the original RSS URL and the redirected URL there. I'm sure that the middle thumbnail image displayed successfully above is for the redirected URL.
